/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;

import logica.Conversion;

/**
 *
 * @author nikom
 */
public class CaF extends javax.swing.JFrame {
	private Conversion caf;

	/**
	 * Creates new form CaF
	 */
	public CaF() {
		initComponents();
		caf = new Conversion();
		
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                tx1 = new javax.swing.JLabel();
                tx2 = new javax.swing.JLabel();
                tx3 = new javax.swing.JLabel();
                bt1 = new javax.swing.JButton();
                txt1 = new javax.swing.JTextField();
                txt2 = new javax.swing.JTextField();
                bt2 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                tx1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                tx1.setText("Convertir a Fahrenheit");

                tx2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                tx2.setText("Ingrese grados celsius");
                tx2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

                tx3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                tx3.setText("Grados Fahrenheit");

                bt1.setText("Convertir ");
                bt1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bt1ActionPerformed(evt);
                        }
                });

                txt1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt1ActionPerformed(evt);
                        }
                });

                txt2.setEditable(false);
                txt2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt2ActionPerformed(evt);
                        }
                });

                bt2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                bt2.setText("Regresar");
                bt2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                bt2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bt2ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txt1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bt2)
                                .addGap(22, 22, 22))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tx3)
                                                        .addComponent(bt1)
                                                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(138, 138, 138)
                                                .addComponent(tx1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(tx2)))
                                .addContainerGap(141, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tx1)
                                .addGap(18, 18, 18)
                                .addComponent(tx2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(bt1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tx3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt2)
                                .addGap(26, 26, 26))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
                PantallaConversion panta = new PantallaConversion();
		panta.setVisible(true);
		panta.setLocationRelativeTo(null);
		dispose();
		
        }//GEN-LAST:event_bt2ActionPerformed

        private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
                try{
			double ca = Double.parseDouble(txt1.getText());
			caf.setgC(ca);
			caf.gcGf();
			txt2.setText(String.valueOf(caf.getgF()));
			
		}
		catch(NumberFormatException ex){
			txt2.setText("No se pueden ingresar letras");
		}
        }//GEN-LAST:event_bt1ActionPerformed

        private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txt1ActionPerformed

        private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txt2ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton bt1;
        private javax.swing.JButton bt2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel tx1;
        private javax.swing.JLabel tx2;
        private javax.swing.JLabel tx3;
        private javax.swing.JTextField txt1;
        private javax.swing.JTextField txt2;
        // End of variables declaration//GEN-END:variables
}
