/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;

import logica.Calculadora;

/**
 *
 * @author nikom
 */
public class Multiplicacion extends javax.swing.JFrame {
	private Calculadora mul;

	/**
	 * Creates new form Multiplicacion
	 */
	public Multiplicacion() {
		initComponents();
		mul = new Calculadora();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                tx1 = new javax.swing.JLabel();
                tx2 = new javax.swing.JLabel();
                tx3 = new javax.swing.JLabel();
                tx4 = new javax.swing.JLabel();
                txt1 = new javax.swing.JTextField();
                txt2 = new javax.swing.JTextField();
                txt3 = new javax.swing.JTextField();
                bt1 = new javax.swing.JButton();
                bt2 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                tx1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                tx1.setText("Multiplicacion");

                tx2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                tx2.setText("ingrese numero 1");

                tx3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                tx3.setText("ingrese numero 2");

                tx4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                tx4.setText("Resultado");

                txt1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt1ActionPerformed(evt);
                        }
                });

                txt2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt2ActionPerformed(evt);
                        }
                });

                txt3.setEditable(false);

                bt1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                bt1.setText("Multiplicar");
                bt1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bt1ActionPerformed(evt);
                        }
                });

                bt2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                bt2.setText("Regresar");
                bt2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bt2ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bt2)
                                .addGap(44, 44, 44))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(tx2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(tx3))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(85, 85, 85)
                                                .addComponent(bt1))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(tx4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addGap(98, 98, 98)
                                                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(145, 145, 145)
                                                .addComponent(tx1)))
                                .addGap(38, 98, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tx1)
                                .addGap(16, 16, 16)
                                .addComponent(tx2)
                                .addGap(13, 13, 13)
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(tx3)
                                .addGap(11, 11, 11)
                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt1)
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tx4)
                                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(bt2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
                PantallaCalculadora panta = new PantallaCalculadora();
		panta.setVisible(true);
		panta.setLocationRelativeTo(null);
		dispose();
        }//GEN-LAST:event_bt2ActionPerformed

        private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txt1ActionPerformed

        private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_txt2ActionPerformed

        private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
                try{
			double num1 = Double.parseDouble(txt1.getText());
			double num2 = Double.parseDouble(txt2.getText());
			mul.setNum1(num1);
			mul.setNum2(num2);
			mul.multiplicacion();
			txt3.setText(String.valueOf(mul.getResultado()));
		}
		catch(NumberFormatException ex){
			txt3.setText("No se puede ingresar letras");
			
		}
        }//GEN-LAST:event_bt1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton bt1;
        private javax.swing.JButton bt2;
        private javax.swing.JLabel tx1;
        private javax.swing.JLabel tx2;
        private javax.swing.JLabel tx3;
        private javax.swing.JLabel tx4;
        private javax.swing.JTextField txt1;
        private javax.swing.JTextField txt2;
        private javax.swing.JTextField txt3;
        // End of variables declaration//GEN-END:variables
}
